variables:
  RELEASE_IMAGE: harbor.ba.de/it-betrieb-ci-cd/ci-cd-test-python:latest

stages:
- build
#- release

before_script:
  - docker login -u robot$it-betrieb-ci-cd+gitlab -p $CI_GITLAB_PASSWORD harbor.ba.de

build:
  stage: build
  script:
    - docker build --pull -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE

#release:
#  stage: release
#  script:
#    - docker pull $TEST_IMAGE
#    - docker tag $TEST_IMAGE $RELEASE_IMAGE
#    - docker push $RELEASE_IMAGE
#  only:
#    - master